#
# Copyright Statement:
#
# Inc: MTK LCM (https://github.com/LCM-MTK)
# Author : Jose (https://github.com/jmpfbmx) and Ruben (https://github.com/ruben1863)
# Telegram Contact: (t.me/LCM-MTK_inc)
# Supported device: Archos AC50FNEV2
# Copyright (C) 2021 : JMPFBMX && Ruben1863
#
#

#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9806e_dsi_vdo_fwvga_ivo_cw_tn_d5270.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
